### ISSUE TITLE
TODO list -- tasks can be found and assigned here

### ISSUE THREAD

**Issue by luap42** [codidact/core#84]
# Codidact core software &mdash; Permanent TODO list
Welcome to the Codidact project. We are glad, that you want to contribute to the software. See [core/CONTRIBUTING.md](https://github.com/codidact/core/blob/develop/CONTRIBUTING.md) for more information, on what kind of contributions are most helpful.

There is a list of open tasks at the bottom of this issue. See through them to find out, what you want to do. Completed tasks will be removed, tasks with a checked box are already assigned. Choose one and write a reply to this issue, saying that you want to claim it.

Claiming an issue means, that you have some responsibility. While this is an open-source project and nobody is paid for their work, we do expect tasks which have been claimed to be completed in a reasonable time. If you suddenly can’t continue, we’d be very glad, if you could give us notice and to publish everything you have already done to save others work.

You should also give us regular feedback. We will host regular meetings on [our Discord server](https://discord.gg/7jf8UzS). We’ll announce a day, on which the feedback should be given there, soon. For all these status updates, ping @StatusUpdates. Just ask in any channel that seems to be appropriate, if you have any questions.
## Todo list

- [ ] a good and easy-to-follow development environment setup guide, ideally containing documentation or linking to official documentation on how to add routes/views/controllers and on how to change the models/db schemata if needed
- [ ] having and deploying a development instance on a cloud service, which always contains the latest develop version
- [ ] creation of user profiles on account creation (registration only creates network-wide “accounts” AFAIK) (models already exist)
- [ ] showing user profiles (connecting with authentification, models already exist)
- [ ] editing user profiles (models already exist)
- [ ] showing questions (models already exist)
- [ ] adding questions (models already exist) 
- [ ] editing questions (models already exist)
- [ ] showing answers to questions (models already exist) 
- [ ] adding answers to questions (models already exist) 
- [ ] adding and editing (changing) votes (models already exist)
- [ ] have and update trust levels (cron task?) (models already exist)
